### ISSUE TITLE
Azure Pipeline Failed

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [HoareLea/SAM_LadybugTools#36]
It seems that after applying Aliases to the references Azure Pipeline has returned failure.

The Aliases have been applied according to description here:
[stackoverflow.com](https://stackoverflow.com/questions/2502640/the-extern-alias-xxx-was-not-specified-in-a-reference-option)

Aliases applied in:
SAM.Analytical.LadybugTools
SAM.Geometry.Grasshopper.LadybugTools

Way Aliases have been implemented:

```
    <PackageReference Remove="Newtonsoft.Json"/>
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.1</Version>
      <Aliases>SAM_Newtonsoft</Aliases>
    </PackageReference>
```

Remove PackageReference implemented accordingly to post on stackoverflow linked above

Source code builds successfully in my Visual Studio

**Comment by willhl** [comment]
Changed build server agent to windows-2019 and added "-t:Restore;Rebuild" to build arguments (as per AIO pipeline).
